// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.OpenInNotepadPlusPlus
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS-OpenInNotepadPlusPlus";
        public const string Name = "Open in Notepad++";
        public const string Description = @"Adds a menu command that lets you open any solution, project, folder and file in Notepad++";
        public const string Language = "en-US";
        public const string Version = "4.1.0";
        public const string Author = "Coding With Calvin";
        public const string Tags = "notepad++, text, code";
    }
}
