// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInNotepadPlusPlus
{
				static class Vsix
				{
								public const string Id = "E476F42B-1D6C-4C78-B56B-42CF7366D5E0";
								public const string Name = "Open in Notepad++";
								public const string Description = @"Adds a menu command that lets you open any solution, project, folder and file in Notepad++";
								public const string Language = "en-US";
								public const string Version = "2.0.0";
								public const string Author = "Calvin A. Allen";
								public const string Tags = "notepad++, text, code";
				}
}
